apiVersion: v1
kind: Pod
metadata:
  name: gleason-shell
spec:
  containers:
  - name: gleason-test
    image: docker.io/jordans1882/gleason-test:v1
    command: ["sleep", "infinity"]
    volumeMounts:
    - name: gleasonvol
      mountPath: /gleasonvol
    resources:
      limits:
        memory: 8Gi
        cpu: "2"
        nvidia.com/gpu: "2"
      requests:
        memory: 8Gi
        cpu: "2"
        nvidia.com/gpu: "2"
  volumes:
  - name: gleasonvol
    persistentVolumeClaim:
        claimName: gleasonvol
  restartPolicy: Never