apiVersion: batch/v1
kind: Job
metadata:
  name: gleason-test
spec:
  template:
    spec:
      containers:
      - name: gleason-test
        image: docker.io/jordans1882/gleason-test:v1
        command:
        - "bash /gleasonvol/test.sh"
        volumeMounts:
        - name: gleasonvol
          mountPath: /gleasonvol
        resources:
          limits:
            memory: 80Gi
            cpu: "25"
            nvidia.com/gpu: "2"
          requests:
            memory: 40Gi
            cpu: "20"
            nvidia.com/gpu: "2"
      volumes:
      - name: gleasonvol
        persistentVolumeClaim:
            claimName: gleasonvol
      restartPolicy: Never
  backoffLimit: 5
